config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'admin/index' => "admin#index"

  resources :users, except: [:destroy, :edit, :update]

  get '/address' => "users#address", as: :new_address

  root 'users#index' 

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user

  after_create :send_thank_you

  private

  def send_thank_you 
    PledgeMailer.thank_you(self.user).deliver
  end 
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :pledge

  #validates :name, presence: true
  
  accepts_nested_attributes_for :pledge

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
  

  def configure_permitted_parameters 
    devise_parameter_sanitizer.for(:sign_up) do |u| 
      u.permit(:name, :password, :address, :email, :password_confirmation, pledge_attributes:[:amount, :frequency, :startdate])
    end 
  end 

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      redirect_to users_path
    else 
      render :new
    end
  end

  def address 
    @user = User.new
  end 

  private 

  def user_params 
    params.require(:user).permit(:name, :address, :email, pledge_attributes: [:amount, :frequency, :startdate])
  end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1> All Pledges </h1> 

<p>
  <%= link_to "Log Out", destroy_user_session_path %> 
</p> 

<ul> 
<% @users.each do |user| %> 
  <p>
  <li>
    Name: <%= user.name%> <br>
    Adderess: <%= user.address %><br>
    Email: <%= user.email %> <br>
    Pledge: <%= user.pledge.try(:amount) %> <br>
    Frequency: <%= user.pledge.try(:frequency) %> <br>
    Start Date: <%= user.pledge.try(:startdate) %> <br>
  </li>
<% end %> 
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Septo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.address %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.address %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/users/address.html.erb
<h1> Add your address to our mailing list </h1>


<%= form_for @user do |f| %> 

<% if @user.errors.any? %> 
  <% @user.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %> </div>
  <% end %> 
<% end %> <br> 

<%= f.label :name %> <br>
<%= f.text_field :name %> <br>

<%= f.label :adderss %> <br>
<%= f.text_field :address %><br> 

<%= f.label :email %> <br>
<%= f.text_field :email %><br> 

<%= f.submit "Add your contact info" %> 

<% end %> 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>About SEPTO</h1>

<br> 

<%= link_to "Pledge Now", new_user_path %> 


Or 

<%= link_to "Sign up for our mailing list", new_address_path %> 

app/views/users/new.html.erb
<h1>Add a New Pledge</h1>

<br> 

<h2><%= link_to "Or Sign up for our mailing list", new_address_path %>  </h2> 


<%= form_for @user do |f| %> 

<% if @user.errors.any? %> 
  <% @user.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %> </div>
  <% end %> 
<% end %> <br> 

<%= f.label :name %> <br>
<%= f.text_field :name %> <br>

<%= f.label :adderss %> <br>
<%= f.text_field :address %><br> 

<%= f.label :email %> <br>
<%= f.text_field :email %><br>

<%= f.label :password %> <br>
<%= f.password_field :password %><br> 

<%= f.label :password_confirmation %> <br>
<%= f.password_field :password_confirmation %><br> 

<hr> 
<%= f.fields_for(:pledge_attributes) do |p| %> 
  <%= p.label :amount %> <br>
  <%= p.number_field :amount %> <br>

  <%= p.label :frequency %> <br>
  <%= p.select :frequency, options_for_select(["Daily", "Weekly", "Monthly"]) %><br>

  <%= p.label :startdate %> <br>
  <%= p.date_field :startdate %><br>
<% end %>
<br>
<hr> 
<%= f.submit "Submit Pledge" %> 

<hr>
<hr>
<% end %> 

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>